controllers
Konkovmax/java-filmorate pull request #1
Opened 2022-08-08 19:33 UTC by Konkovmax

2022-08-08 19:46 UTC, Konkovmax commented
сначала я сделал всё для user ов, потом прочитал доп задание про @validated и мне очень приглянулась
  эта идея, поэтому film-ы я делал через @valid то есть одно так второе подругому, но ТЗ не противоречит,
   поэтому оставил так

2022-08-09 19:44 UTC, FanaticFiz requested changes
Финальный коммент на Я.Практикуме

2022-08-09 19:44 UTC, FanaticFiz commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Увидел у тебя заголовок: "Version 1.0" - подумал, ну сейчас мы посмотри точно ли у него версия 1.0 )))

Ну собственно, НЕТ ! ))

Советую прочитать про семантическое версионирование, ну а после не стесняйся, смело проставь версию!

2022-08-09 19:44 UTC, FanaticFiz commented on pom.xml
> +	</properties>
А `pom` файл желательно бы причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как parent, properties, dependencies

Хорошим тоном будет указать кодировку в properties
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //сначала я сделал всё для user ов, потом прочитал доп задание про @validated и мне очень приглянулась
К сведению принято ))

А ты там случайно не забыл как писать многострочные комментарии? ))

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    AtomicInteger atomicInteger = new AtomicInteger(0);
Обоснуй выбор `AtomicInteger`

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else {
Будет лучше без `else` 
По условию будет бросаться ексепшн, далее просто тот же код но на одном уровне, без вложенности...

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Film currentFilm : films) {
Ну и спрашивается куда делись те знания и приёмы, которые отрабатывались на предыдущих работах...

Твоё приложение будет быстро деградировать с ростом списка. 

Дальше не комментирую, жду решения.....

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().isEmpty()) {
Это что то очень странное... такого быть не должно.
Ты тут смешал валидацию и бизнес код, раздели его.

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        //удобнее это было бы сделать через MAP, но в  ТЗ и в постмэне везде про список, поэтому сделал
Это была проверка и ты её не прошел ))
_шутка_

Тут же дело не в удобстве, ну да я уже прокомментировал ранее, а потом нашел этот твой коммент )

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandlingControllerAdvice.java
> +public class ErrorHandlingControllerAdvice {
Ну с этим ты кажется забежал вперёд. Хорошо что разобрался.

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends RuntimeException {
Нет наследование верно.
Название надо другое, а именно BadRequestException потому как в веб сервисе мы именно так отвечаем на запросы с не корректными параметрами.

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/Violation.java
> +    private final String fieldName;
Just `field`

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/tests/FilmControllerTest.java
> +package ru.yandex.practicum.filmorate.tests;
Тестам не место среди кода.
У тебя же сформировался каталог для тестов, почему тесты не там?

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/validator/ReleaseDate.java
> +public @interface ReleaseDate {
Ну всё, пошли понты! ))
Ну что тут скажешь, молодец!

2022-08-09 19:44 UTC, FanaticFiz commented on src/main/resources/application.properties
> +
Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате yaml -> application.yml

Соответственно - попрошу тебя этому следовать.
Как мини задание: посмотри как задавать порт для сервиса отличный от дефолтного и случайный.
(Сам порт менять не нужно, сломаются тесты)

2022-08-09 19:46 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandlingControllerAdvice.java
> +package ru.yandex.practicum.filmorate.exceptions;
Следуй единому принципу именования пакетов. Определись во множественном числе или единственном тебе сейчас кажется более уместным. Но точно не в разнобой: `controller` / `exceptions`

2022-08-10 17:37 UTC, Konkovmax commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Сделал 0.1.1, т.к. исправил ошибки, а предыдущая, согласно semver.org должна была быть 0.1.0

2022-08-10 17:42 UTC, Konkovmax commented on pom.xml
> +	</properties>
исправил

2022-08-10 17:52 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    AtomicInteger atomicInteger = new AtomicInteger(0);
В приложении канбан у меня был метод, который увеличивал id... Но когда я увидел, что здесь всё делается автоматически, @Data и прочие прибамбасы, я подумал, что вставлять этот метод сюда - не серьезно и надо искать что-то более изящное. Нашел атомик интеджер, подумал, почему бы и нет

2022-08-10 18:13 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends RuntimeException {
исправил

2022-08-10 18:14 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/Violation.java
> +    private final String fieldName;
исправил

2022-08-10 18:14 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/tests/FilmControllerTest.java
> +package ru.yandex.practicum.filmorate.tests;
исправил

2022-08-10 18:21 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/validator/ReleaseDate.java
> +public @interface ReleaseDate {
Спасибо! Просто, когда читаешь в слаке, что творят остальные, не хочется от них отставать. Но при этом, я помню, что ты писал, что тем кто рано присылает работу, ты даешь самые интересные доп. задания и хочется отправить поскорее. Тут просто победило любопытство))) "Что и так можно???" "И вот так???" "Вот это да!!!"

2022-08-10 18:21 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandlingControllerAdvice.java
> +package ru.yandex.practicum.filmorate.exceptions;
исправил

2022-08-10 18:45 UTC, Konkovmax commented on src/main/resources/application.properties
> +
Я добавил другие порты и закомментировал их, чтобы ничего не сломать

2022-08-11 04:55 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else {
исправил

2022-08-11 04:55 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Film currentFilm : films) {
переделал через мэп

2022-08-11 04:55 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().isEmpty()) {
исправил

2022-08-12 11:06 UTC, FanaticFiz requested changes
А так?

2022-08-12 11:06 UTC, FanaticFiz commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
`<version>0.0.1-SNAPSHOT</version>` а где ты версию поменял? ))

2022-08-12 11:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) throws BadRequestException {
`throws BadRequestException` не нужно это не checked ексепшн.

2022-08-12 11:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film update(@RequestBody Film film) {
А разве нам не надо провалидировать сущность при обновлении так же как и при создании?

2022-08-12 11:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public boolean userValidate(User user) throws BadRequestException {
Валидатор должен заниматься только своим делом - валидировать. 
Поэтому нужно:
или переназвать метод(легче) 
или сначала провалидировать а потом на основе полученной информации бросить ексепшн(сложнее)

2022-08-13 04:25 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) throws BadRequestException {
почему то у комментария про <version>0.0.1-SNAPSHOT</version> а где ты версию поменял? )) нет окошка для реплая, поэтому тут напишу. Я поменял там где было 1.0 в комментариях к комиту и в названии пулреквеста, а в пом было не 1.0 поэтому про него я не подумал. Но т.к. ты подсветил его, то теперь поменял и там(теперь каждый раз переписывать???), пулреквест переименовал, т.к. понял, что каждый раз его менять на другую версию - не вариант.

эксепшн вообще убрал, т.к. вспомнил, что я как раз для этого случая сделал свой кастомный валидатор

2022-08-13 04:25 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film update(@RequestBody Film film) {
добавил

2022-08-13 04:31 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public boolean userValidate(User user) throws BadRequestException {
переименовал. Этот способ был помечен как "легче" и были сомнения, а не обленился ли я, но успокоил себя тем, что не очевидно, что "сложнее" - значит лучше

2022-08-13 05:22 UTC, FanaticFiz approved these changes

2022-08-13 05:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
Я буду придирчив, ну а на самом деле просто проверяю точно так же как я это делаю на работе )

Если это не будешь исправлять ты то это придётся делать коллегам...

Лишние пустые строки в конце.
Файл должен заканчиваться одной пустой строкой.

2022-08-13 05:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new NotFoundException("film not found");
Давай больше информации при возникновении ошибки.
Тебе же не составит труда сказать какой именно фильм не найден. 
Чаще всего говорят именно о том параметре по которому искали, т.е. `Фильм не найден по id: 314` / 
`Фильм с id: 314 не найден`

2022-08-13 05:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public boolean userRequestCheck(User user) throws BadRequestException {
Если метод заточен на то чтобы кидать ексепшены то надо его так и назвать: `throwIfNotValid`
Возвращать ничего не надо, метод или кинет исключение или всё будет хорошо.
Условие в коде не нужно будет и код станет проще.

```
    public User create(@Valid @RequestBody User user) {
        throwIfNotValid(user);
        
        if (user.getName().isEmpty()) {
                user.setName(user.getLogin());
                user.setId(atomicInteger.incrementAndGet());
                users.put(user.getId(), user);
                log.warn("Name is empty. Login is used as a name.");
                return user;
        }

        user.setId(atomicInteger.incrementAndGet());
        users.put(user.getId(), user);
        log.info("User added");
        
        ....
```

2022-08-13 05:22 UTC, FanaticFiz commented on src/main/resources/application.yml
> +#server:
Старый файл .properties удали

2022-08-13 05:24 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) throws BadRequestException {
Теперь каждый раз переписывать???

Ну вообще да, так это и происходит. 
Но это не обязательно конечно...

2022-08-14 08:17 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
Пока, как ты выразился "по времени не горим", готов доводить код до совершенства столько сколько понадобится. Исправил)

2022-08-14 08:18 UTC, Konkovmax commented on src/main/resources/application.yml
> +#server:
удалил

2022-08-14 09:03 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new NotFoundException("film not found");
исправил

2022-08-14 09:07 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public boolean userRequestCheck(User user) throws BadRequestException {
круто. Исправил.

2022-08-14 09:15 UTC, merged