Add reviews
Konkovmax/java-filmorate pull request #11
Opened 2022-10-05 06:18 UTC by Konkovmax

2022-10-05 11:59 UTC, AleksKras requested changes

2022-10-05 11:59 UTC, AleksKras commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundException(String.format(
На мой взгляд, эксепшн о не найденном пользователе можно выбрасывать в методе проверки наличия пользователя. тогда можно будет избежать повторение блоков кода с условием, логированием и генерацией эксепшена. Плюс метод userExistCheck практически дублирует метод getUser.

2022-10-05 11:59 UTC, AleksKras commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            Collections.sort(reviews, comparator);
сортировку и return можно вынести из цикла, тогда код не будет дублироваться

2022-10-05 11:59 UTC, AleksKras commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public ReviewService(ReviewDbStorage reviewStorage, UserDbStorage userStorage, FilmDbStorage filmStorage) {
Как вариант - можно воспользоваться аннотацией @requiredargsconstructor

2022-10-06 06:07 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundException(String.format(
я сначала так и сделал, но ревьювер сказал, что storage только работа c базой, а всё остальное, в т.ч. проверки и эксепшены - в Сервис

2022-10-06 06:10 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            Collections.sort(reviews, comparator);
Это да, спасибо! проглядел...

2022-10-06 06:15 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public ReviewService(ReviewDbStorage reviewStorage, UserDbStorage userStorage, FilmDbStorage filmStorage) {
Хорошая идея, исправил

2022-10-06 06:36 UTC, AleksKras commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundException(String.format(
тогда получается лучше не через UserStorage проверять/получать пользователя, а через UserService. но думаю это не критично.

2022-10-06 06:36 UTC, AleksKras approved these changes

2022-10-06 19:55 UTC, baston7 approved these changes

2022-10-06 19:59 UTC, merged