Develop
Konkovmax/java-filmorate pull request #18
Opened 2022-10-09 13:54 UTC by Konkovmax

2022-10-09 14:01 UTC, Konkovmax commented
Мы не стали дожидаться, пока доделает ветку add-feed, участник, который всё это время заканчивал 12-й спринт, Т.к. требуемые 18 сторипоинтов набралось и затягивать - не хотелось бы. При этом соответствующий тест постмана  на add-feed не проходит. Это нормально?

2022-10-10 00:59 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-10 00:59 UTC, FanaticFiz commented on .gitignore
> +.gitignore
Привет!
Забавно, зачем добавили в файл `.gitignore` самого себя? )

А еще и конфиги приложения?

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "DIRECTOR"
Внимательнее! 
В этом sql уже есть создание такой таблицы!

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE "REVIEWS" (
Это безобразие надо выровнять...

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE "REVIEW_SCORES" (
Диаграмма `Diagram1.png` теперь не отображает действительности.

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    boolean delete(int userId);
Удаление можно сделать `void`. 
Так например сделано у JPA репозиториев. 
Ну т.е. или операция завершиться успешно или упадет с ексепшеном, который можно перехватить.

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        String createQuery = "delete from USERS where userid = ?";
В соседнем файле видел красивый запрос 
`DELETE FROM reviews WHERE reviewid = ?`
т.е. операции sql написаны в верхнем регистре всё остальное в нижнем...

Тут же сделано наоборот ))
А в целом по коду то так то сяк, что естественно некрасиво/не читаемо.

Я позволю вам самим в команде определиться как вы хотите это видеть, но нужно чтобы было везде одинаково!

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        else {
`else`  не должен быть на новой строке - это не по джавовски...

```
} else {
```

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +        return null;
Код не выровнен по принятому code style.

Пустые строки 55,56 тоже лишние!

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +        List <Genre> genres  = jdbcTemplate.query(createQuery, this::mapRowToGenre, filmId);
Куда не глянь у вас везде одни `createQuery` ! ))

Либо вы пишите более обще: `query` и тогда копипаста не будет заметна, либо не забывайте менять! ))

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public void delete(@PathVariable("id") Integer filmId) { filmService.delete(filmId); }
Мы не пишем всё в одну строку!
Соблюдайте `code style`

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getPopular(@RequestParam(value = "genreId", required = false) Integer genreId,
Кажется так выглядит куда приятнее: 

```
    @GetMapping("/films/popular")
    public List<Film> getPopular(@RequestParam(value = "genreId", required = false) Integer genreId,
                                 @RequestParam(value = "count", defaultValue = "10", required = false) int count,
                                 @RequestParam(value = "year", required = false) Integer year) {
        return filmService.getPopular(year, genreId, count);
    }
```

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +    public List<Review> getAllReviews(@RequestParam(value = "filmId", defaultValue = "0", required = false) Integer filmId,
Тут превышены допустимые 120 символов в строку...
Просто делаем перенос: 

```
    @GetMapping("/reviews")
    public List<Review> getAllReviews(
            @RequestParam(value = "filmId", defaultValue = "0", required = false) Integer filmId,
            @RequestParam(value = "count", defaultValue = "10", required = false) Integer count) {
        return reviewService.getAllReviews(filmId, count);
    }
```

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (sortBy.equals("year")) {
При необходимости такого сравнения лучше "перевернуть", чтобы избежать неприятной ошибки
`sortBy.equals("year") -> "year".equals(sortBy)`
Т.е. метод equals лучше вызывать у заранее известной строки.

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +
В каждом файле бардак с code style - что меня совсем не радует...

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +public class DirectorService {
Этот сервис получился вовсе не сервис!
У вас всё всё упало на самый нижний уровень на хранилище, а этот класс просто как призрак транслирует запросы в хранилище... при таком подходе он вовсе не нужен получается.

Хранилище должно только работать с базой, весь остальной код должен быть тут.

Например, вот это из хранилища должно быть в сервисе.
```
.stream().findFirst()
                .orElseThrow(() -> new NotFoundException(String.format(
                        "Director with id: %s not found",
                        directorId)));
```

Логика/эксепшены реализуются в сервисах.

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public List<Director> findAllDirectors() {
Некорректные и избыточные названия методов!
Зачем называть `findAllDirectors` ? 
Метод не висит в воздухе! Мы находимся в контексте класса о `Director` поэтому просто: `findAll()`

2022-10-10 00:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if(film.getGenres() != null && film.getGenres().size() > 0){
Вас не смущает то что `film.getGenres()` запрошено три раза всего на двух строках кода??? ))

Вынесите в переменную сначала потом работаёте с ней...

И снова таки `code style` настройте среду разработки
`if пробел (film.getGenres()` 
`.size() > 0) пробел {`

2022-10-10 00:59 UTC, FanaticFiz commented on .gitignore
>  *.jar
Напишу некоторые общие замечания тут
1. Не хватает вот этого "Обязательно должно быть описание того, какие задачи выполнила группа, в описании пул-реквеста или в файле readme"

2. Никто из группы не представился в git корректно
![image](https://user-images.githubusercontent.com/3994663/194787513-328a2ed1-72bb-4560-89a8-a877fd6e1e4e.png)

2022-10-10 00:59 UTC, FanaticFiz commented on .gitignore
> +.gitignore
Почему вы решили добавить в игнор это?

2022-10-11 08:32 UTC, merged

2022-10-11 17:45 UTC, Konkovmax commented on .gitignore
> +.gitignore
Это я не заметил, там были сложности с подключением базы через application.yml, и начали решать это через гитигнор... но получилось как-то так

2022-10-11 17:46 UTC, Konkovmax commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "DIRECTOR"
исправил

2022-10-11 17:59 UTC, Konkovmax commented on src/main/resources/schema.sql
> +CREATE TABLE "REVIEWS" (
Если ты про лишние строчки - то убрал. Или плохо что ");" на новой строке? это вроде бы идея так ставит сама

2022-10-11 18:35 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    boolean delete(int userId);
исправил

2022-10-11 18:47 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        else {
исправил

2022-10-11 18:48 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +        return null;
исправил

2022-10-11 18:53 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +        List <Genre> genres  = jdbcTemplate.query(createQuery, this::mapRowToGenre, filmId);
не совсем понял, как по другому назвать строку создающую запрос.... То есть поменять на query - не проблема, но интересно чем хуже везде createquery, а не query

2022-10-11 19:03 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public void delete(@PathVariable("id") Integer filmId) { filmService.delete(filmId); }
исправил

2022-10-11 19:05 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getPopular(@RequestParam(value = "genreId", required = false) Integer genreId,
согласен на 100%

2022-10-11 19:06 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +    public List<Review> getAllReviews(@RequestParam(value = "filmId", defaultValue = "0", required = false) Integer filmId,
исправил

2022-10-11 19:09 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (sortBy.equals("year")) {
готово

2022-10-11 19:11 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +
:( исправил

2022-10-11 20:01 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if(film.getGenres() != null && film.getGenres().size() > 0){
так-то смущает, но видимо в процессе такая мысль не пришла. исправил

2022-10-11 20:02 UTC, Konkovmax commented on .gitignore
>  *.jar
имена, мы сделали, но на старое, я так понял уже не изменить, а новое должно быть красиво

2022-10-11 20:02 UTC, Konkovmax commented on .gitignore
> +.gitignore
ответил выше

2022-10-12 07:27 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public List<Director> findAllDirectors() {
findAllDirectors исправил, но в ведь по сути у нас везде такое, getFilm, crateUser, addLike. И не получится ли, что если убрать упоминание сущностей, то будет куча гетов и криэйтов, в которых можно легко запутаться?