Develop
Konkovmax/java-filmorate pull request #26
Opened 2022-10-11 20:37 UTC by Konkovmax

Выполнили все задачи, которые были в ТЗ:
Добавлены такие функциональности как  поиск, лента событий, общие фильмы, рекомендации и  отзывы.
Добавлены режиссёры к фильмам
Сделали удаление фильмов и пользователей и вывод самых популярных фильмов по жанру и годам

2022-10-12 19:01 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-12 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/EventController.java
> +        return service.getAllEvents(userId);
Коллеги лучше делать наоборот.
`EventService service` назвать `EventService eventService`
а
методы называть короче: `getAllEvents -> getAll` 

`eventService.getAll(userId);`

2022-10-12 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/EventController.java
> +        return service.getAllEvents(userId);
В других сервисах так же.
Делайте проще названия методов. Тогда вам легче будет увидеть что многие сервисы, например, очень похожи по своим методам и этим можно пользоваться!

2022-10-12 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
>          return reviewService.getAllReviews(filmId, count);
`getAllReviews -> getAll()`
`removeReview -> remove` а может `delete`? 
Ведь у вас 
`deleteDirector` который надо `delete`
`userService.delete()`

Соблюдайте консистентность в именованиях!

2022-10-12 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventStorage.java
> +package ru.yandex.practicum.filmorate.storage;
Почему до сих пор не пришли к единому подходу в именовании пакетов?
`controllers`, `exceptions`... но
`service`, `storage`...

2022-10-12 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventStorage.java
> +    void addEvent(Event event);
Хочется от вас большего использования интерфейсов...
Более универсальные интерфейсы! Дженерики...

Интерфейсы как у хранилищ, так и у сервисов !

Покажите что вы можете круче!
Ведь с сутевой частью работы вы справились - справились хорошо! И с SQL справились...

Остался контрольный в голову сделать и ревьюер будет повержен! )))

2022-10-12 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDbStorage.java
> +        String sql = "DELETE FROM films_directors WHERE directorid=?";
Помните что это можно было бы решить и на уровне SQL каскадированием...

2022-10-12 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            Event friendEvent = new Event(userId, "FRIEND", "REMOVE");
"FRIEND", "REMOVE" - `enum` не подвезли? 
Осознанный ли это выбор?

2022-10-12 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final Comparator<Review> comparator = Comparator.comparingInt(Review::getUseful).reversed();
Ну нельзя так делать! 
Как это идут методы публичные - тут бац посреди приватный компаратор вырос! ))

Помните что в классе расположение методов тоже регламентируется, сначала публичные потом приватные методы.

Далее, а нужен ли тут компаратор, по одному параметру?
С этим отлично справиться SQL им тоже можно отсортировать...

2022-10-12 19:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
На примере метода getReview()
- можно инвертировать условие
- избавиться от лишнего else
- добавить логирования

```
    public Review getReview(int reviewId) {
        if (reviewStorage.getReview(reviewId).isEmpty()) {
            String msg = String.format("Review with id: %s not found", reviewId);
            log.debug(msg);

            throw new NotFoundException(msg);
        }
        
        return reviewStorage.getReview(reviewId).get();
    }
```



А можно:
- написать в одну строку пользуясь Optional
- избавиться от String.format перефразировав предложение

```
    public Review getReview(int reviewId) {
        return reviewStorage.getReview(reviewId)
                            .orElseThrow(() -> new NotFoundException("Not found review with id: " + reviewId));
    }
```

Какой вариант вам больше нравиться? ))

Постарайтесь найти в коде еще места где можно провести подобный рефакторинг!

2022-10-13 01:55 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/EventController.java
> +        return service.getAllEvents(userId);
Иван

2022-10-13 01:55 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
>          return reviewService.getAllReviews(filmId, count);
Максим

2022-10-13 02:00 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventStorage.java
> +package ru.yandex.practicum.filmorate.storage;
исправил, загрузите, пожалуйста, новый вариант

2022-10-13 02:01 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventStorage.java
> +    void addEvent(Event event);
Алексей?

2022-10-13 02:01 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDbStorage.java
> +        String sql = "DELETE FROM films_directors WHERE directorid=?";
Сергей?

2022-10-13 02:01 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            Event friendEvent = new Event(userId, "FRIEND", "REMOVE");
Иван

2022-10-13 02:02 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final Comparator<Review> comparator = Comparator.comparingInt(Review::getUseful).reversed();
Максим

2022-10-13 02:02 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
Максим

2022-10-13 18:26 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
>          return reviewService.getAllReviews(filmId, count);
исправил

2022-10-13 18:39 UTC, baston7 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/EventController.java
> +        return service.getAllEvents(userId);
исправил

2022-10-13 19:04 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDbStorage.java
> +        String sql = "DELETE FROM films_directors WHERE directorid=?";
исправил

2022-10-13 19:08 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final Comparator<Review> comparator = Comparator.comparingInt(Review::getUseful).reversed();
компаратор перенёс, а с sql меня видимо смутило, что там разные методы, оба менять хорошо ли это.... Но теперь понятно, надо было менять

2022-10-13 19:15 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
В одну строчку - это конечно здорово получилось...

2022-10-14 04:04 UTC, FanaticFiz approved these changes

2022-10-14 04:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/services/BasicService.java
> +abstract class BasicService<T> {
Ага, вот оно что, вы соорудили абстрактный класс! 
Это сложнее чем просто интерфейсы, и получается что вы и одновременно и молодцы, но и сделали не то ))
Ну как не то, не то что я имел ввиду, ну да то мои проблемы - надо научиться яснее изъяснятся )
Так что без всяких но - вы оказались очень круты! ))

2022-10-14 04:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/services/GenreService.java
> +    public Genre getById(int genreId) {
Не поленюсь еще раз подсветить вам этот момент...
Когда у вас есть Optional

```
    public Genre getById(int genreId) {
        return genreStorage.getById(genreId)
                           .orElseThrow(() -> new NotFoundException("Not found genre with id: " + genreId));
    }
```

2023-02-10 06:25 UTC, merged