Add database
Konkovmax/java-filmorate pull request #3
Opened 2022-09-18 09:53 UTC by Konkovmax

2022-09-18 17:44 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/Service/FilmDbService.java
>  import org.springframework.stereotype.Service;
Как же так получилось что мы всё еще не переименовали пакет `Service` согласно правилам именования пакетов? Это надо исправить.

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/Service/FilmDbService.java
>  public class FilmDbService {
Нет тут тебя занесло не туда... не нужно было делить сервисы на `db`, `inMemory`. Это в целом плохая идея!
Ты всегда держи в голове что программисты люди ленивые, по хорошему ленивые.
Ленивый программист не станет делать и два сервиса и два стора. 
Поэтому, как только ты видишь что тебе нужно написать какую то кучу классов или проделать кучу работы, ну ты посомневайся немного, приди ко мне в slack с вопросом!

Давай вообще отказываться от inMemory хранилища. Это пройденный этап, сосредотачиваемся на БД.

2022-09-18 17:44 UTC, FanaticFiz commented on pom.xml
> +		<dependency>
Не та зависимость подключена.
Ты должен чётко понимать разницу между `jdbc` и `jpa`
Сейчас нужно подключить JDBC
У тебя всё работает так как jpa включает в себя jdbc

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/Service/FilmDbService.java
> +    public List<Genre> findGenres() {
Теперь по содержанию сервиса.
Это сервис фильмов тут не место методам про жанры и mpa!

Да, этот сервис, может и будет включать в себя хранилище жанров например, чтобы насытить сущность фильма этой инфой, но только для этого.

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/Service/UserDbService.java
> +    /* в ТЗ сказали использовать @Qualifier, но чтобы его задействовать мне пришлось в интерфейс добавить методы, которые
Да вижу, но в эталонной реализации, кстати, уже нет реализации inMemroy, поэтому и @Qualifier нет, так что если ты выпилишь их тоже, работу можно будет принимать.

Но в целом, я очень ЗА, чтобы студенты познакомились с таким механизмом(@Qualifier), это очень полезно...

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>          return film;
Кстати, ты возвращаешь ту же самую сущность что и пришла `film`.
А надо возвращать то что вернёт сервис.

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @GetMapping("/genres")
`/genres`, `/mpa` это должно находится в своих собственных контроллерах.
Плохо в одном контроллере иметь разные корневые маппинги...

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres = new ArrayList<>();
Сделай отступ между полями...

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/GenreTypes.java
> +// Хотел удалить, но не стал, т.к. у нас интерфес, для разных версий(БД и без БД) и в теории это тоже нужно будет...?
ну наверное, пока ты досюда дочитал, то понял что нет, не нужен... ))

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
Ну во первых, публичное, да еще и статическое поле ты должен был разместить выше приватных.
НУ а во вторых, не место ему тут, ты вон даже в фильмы его потащил. 
Оно должно быть расположено где то выше, в коком нить конфигурационном файле, ну или если такового не предвидится, можно унести к классу точке входа в приложение, т.е. в FilmorateApplication

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sqlQuery = "insert into films(Name, DESCRIPTION, DURATION, RELEASEDATE, RATING) " +
То что это `sqlQuery` эт понятно, напиши лучше `createQuery`.

Далее... я обычно рекомендую привыкать писать upparcas-ом команды SQL, а все остальное малыми...
А у тебя вижу ровно обратный подход, забавно )

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Mpa getMpa(int MpaId) {
Ну и опять же тут перемешано и фильмы и mpa и жанры...
У них свой storage!

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "USERS"
Таблицы и поля в них, в SQL принято называть малыми буквами (в нижнем регистре),
в одно слово или с разделителем `_`

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "RATINGS"
`mpa` четко отражает какой это рейтинг. Таблицу лучше назвать именно так.

2022-09-18 17:44 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    "RATING"      INT     NOT NULL,
"RATING" неправильно, это не сам рейтинг а его id, причем не вижу чтобы это было оформлено как связь...

2022-09-19 18:32 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/Service/FilmDbService.java
>  import org.springframework.stereotype.Service;
сделано

2022-09-19 18:39 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/Service/FilmDbService.java
>  public class FilmDbService {
убрал InMemory версию

2022-09-19 18:53 UTC, Konkovmax commented on pom.xml
> +		<dependency>
исправил

2022-09-19 19:00 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/Service/UserDbService.java
> +    /* в ТЗ сказали использовать @Qualifier, но чтобы его задействовать мне пришлось в интерфейс добавить методы, которые
убрал

2022-09-19 19:00 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>          return film;
исправил, я так понял, что это проблема не конкретного метода, поэтому везде поменял

2022-09-19 19:06 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres = new ArrayList<>();
строку добавил, но мысль, если честно не понял

2022-09-19 19:06 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/model/GenreTypes.java
> +// Хотел удалить, но не стал, т.к. у нас интерфес, для разных версий(БД и без БД) и в теории это тоже нужно будет...?
выпилил))

2022-09-20 16:06 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/Service/FilmDbService.java
> +    public List<Genre> findGenres() {
убрал

2022-09-20 16:06 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @GetMapping("/genres")
сделал отдельные контроллеры

2022-09-20 16:09 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
перенес в FilmorateApplication

2022-09-20 16:19 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sqlQuery = "insert into films(Name, DESCRIPTION, DURATION, RELEASEDATE, RATING) " +
исправил

2022-09-20 16:20 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Mpa getMpa(int MpaId) {
сделал всем по storage

2022-09-20 19:29 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sqlQuery = "insert into films(Name, DESCRIPTION, DURATION, RELEASEDATE, RATING) " +
про uppercase - это мне IDEA сама так подставляет. я не стал менять. Или это надо где-то в настройках идеи менять?

2022-09-20 19:35 UTC, Konkovmax commented on src/main/resources/schema.sql
> +    "RATING"      INT     NOT NULL,
ALTER TABLE "FILMS"
    ADD CONSTRAINT "FK_FILMS_RATING" FOREIGN KEY ("RATING")
        REFERENCES "RATINGS" ("RATINGID");
вот тут это было как связь оформлено

2022-09-20 19:55 UTC, Konkovmax commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "USERS"
я сначала так и сделал - всё маленькими, но была ошибка Table "MPA" not found (candidates are: "mpa"); и я решил, что для базы Н2 принципиально, чтобы большими буквами всё писать и исправил на большие

2022-09-20 21:13 UTC, Konkovmax commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "RATINGS"
исправил. правда не придумал, как реформатить код при изменении БД и пришлось вручную перелопатить

2022-09-20 21:14 UTC, Konkovmax commented on src/main/resources/schema.sql
> +    "RATING"      INT     NOT NULL,
ALTER TABLE "FILMS"
    ADD CONSTRAINT "FK_FILMS_RATING" FOREIGN KEY ("MPAID")
        REFERENCES "MPA" ("MPAID");

2022-09-20 21:14 UTC, Konkovmax commented on src/main/resources/schema.sql
> +    "RATING"      INT     NOT NULL,
теперь вот так

2022-09-21 06:42 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    "RATING"      INT     NOT NULL,
да, тут я был не внимателен...

2022-09-21 07:16 UTC, FanaticFiz requested changes
Надо разобраться с зонами ответственности между хранилищами и сервисами.

2022-09-21 07:16 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmDbService filmService;
Не нужно добавлять `Db` в название... Это сервис для сущности фильмов, всё!
В сервисе мы ходим в базу, ходим на файловую систему, можем выполнять 
http запросы, общаться с очередями, в общем ты понял )

2022-09-21 07:16 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +    private final GenreDbService genreService;
ну соответственно везде вставка db лишняя

2022-09-21 07:16 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres = new ArrayList<>();
ну вообще я предпочитаю видеть поля класса вместе, ну вот например:

```
    private String token;
    private String dateTime;
    private String actionType;
    private String entityName;
    private String entityType;
    private Long entityId;
```

Но когда появляются аннотации, то всё превращается в кашу и хочется отделить каждое поле друг от друга

```
    @NotBlank
    @Size(min = 3, max = 20)
    private String actionType;

    @Size(max = 700)
    private String entityName;

    @Size(min = 3, max = 50)
    private String entityType;
```

2022-09-21 07:16 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            throw new NotFoundException(String.format(
Посмотри на сервис... такое ощущение что он вообще как не нужная прослойка, просто транслирует всё в хранилище.
И что мы видим тут? Что хранилище у тебя занимается буквально всем!

Такого быть не должно... Хранилище только ходит за данными. 
Сервис должен кидать `NotFoundException` если хранилище сказало что такой записи нет! Это вот самый яркий пример...

2022-09-21 07:16 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public List<Film> findAll() {
Вот пример хорошего метода в хранилище, просто сходили за данными и вернули ничего больше.... выводы по данным сделает сервис, если нужно

2022-09-21 18:38 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmDbService filmService;
исправил

2022-09-21 18:40 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            throw new NotFoundException(String.format(
теперь понял про пробелы, переделал

2022-09-22 19:56 UTC, Konkovmax commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            throw new NotFoundException(String.format(
Исправил, всё что нашел перенес в сервис. Из остальных файлов тоже

2022-09-23 05:40 UTC, FanaticFiz approved these changes

2022-09-30 09:06 UTC, merged